"""PR description entity."""

from pydantic import BaseModel, ConfigDict, Field


class PRDescription(BaseModel):
    """Immutable PR description generated by AI."""

    model_config = ConfigDict(frozen=True)

    content: str = Field(description="Full PR description content")
    ai_provider: str = Field(default="unknown", description="AI provider that generated this")

    @property
    def is_empty(self) -> bool:
        """Check if content is empty or whitespace."""
        return not self.content.strip()
